openapi: 3.0.0
info:
  title: technopolis
  version: 1.0.0
  license:
    name: GNU Free Documentation License Version 1.3
    url: 'https://www.gnu.org/licenses/fdl-1.3.txt'
  contact:
    url: 'https://discord.gg/PBp8rJt'
    name: Technopolis official Discord server
  description: |-
    Technopolis is a globally interconnected micro-blogging platform inspired by Misskey.

    Notes on using the API:
    When using Mastodon-compatible API, set Content-Type header to "application/x-www-form-urlencoded".
servers:
  - url: 'http://technopolis.example'
    description: ''
paths:
  /api/v1/apps:
    post:
      summary: Create an application アプリケーションの作成
      operationId: post-apps
      description: |-
        Create new application to obtain OAuth2 credentials.

        OAuth2資格を取得するためのアプリケーションを作成します。
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_name:
                  type: string
                redirect_uris:
                  type: string
                scopes:
                  type: string
                website:
                  type: string
              required:
                - client_name
                - redirect_uris
            examples: {}
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  type: string
                redirectURIs:
                  type: string
                scopes:
                  type: string
                website:
                  type: string
              required:
                - clientName
                - redirectURIs
            examples: {}
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: string
                  name:
                    type: string
                  website:
                    type: string
                  redirectURIs:
                    type: string
                  clientID:
                    type: string
                  clientSecret:
                    type: string
              examples:
                example:
                  value:
                    id: 1043b2e7-a225-467c-9995-73eb33ae6f1e
                    name: Example of the application
                    website: null
                    redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'
                    client_id: EXAMPLE OF CLIENT ID
                    client_secret: EXAMPLE OF CLIENT SECRET
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
    parameters: []
  /api/v1/apps/verify_credentials:
    get:
      summary: Verify your app works アプリケーションの動作確認
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  website:
                    type: string
              examples:
                example:
                  value:
                    name: Example of application
                    website: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      operationId: get-apps-verify_credentials
      description: |-
        Confirm that the app's OAuth2 credentials work.

        アプリケーションのOAuth2認証情報が正しく機能することを確認します。
      parameters:
        - schema:
            type: string
            example: Bearer <OAuth2 token>
            pattern: ''
          in: header
          name: Authorization
          required: true
          description: Bearer <OAuth2 token here>
    parameters: []
  /oauth/authorize:
    get:
      summary: Authorize a user ユーザーの承認
      tags: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      operationId: get-oauth
      description: |-
        Displays an authorization form to the user. If approved, it will create and return an authorization code, then redirect to the desired redirect_uri, or show the authorization code if urn:ietf:wg:oauth:2.0:oob was requested. The authorization code can be used while requesting a token to obtain access to user-level methods.

        承認フォームをユーザーに表示します。 承認されると認証コードを作成して返し、目的のredirect_uriにリダイレクトするか、urn:ietf:wg:oauth:2.0:oobがリクエストされた場合は認証コードを表示します。 ユーザーレベルのメソッドへのアクセスを取得するためにトークンを要求するときに認証コードを使用することができます。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forceLogin:
                  type: boolean
                responseType:
                  type: string
                clientID:
                  type: string
                redirectURI:
                  type: string
                scope:
                  type: string
              required:
                - responseType
                - clientID
                - redirectURI
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                force_login:
                  type: boolean
                response_type:
                  type: string
                client_id:
                  type: string
                redirect_uri:
                  type: string
                scope:
                  type: string
              required:
                - response_type
                - client_id
                - redirect_uri
            examples: {}
        description: ''
    parameters: []
  /oauth/token:
    post:
      summary: Obtain a token トークンの入手
      operationId: post-oauth-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  scope:
                    type: string
                  created_at:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      description: |-
        Returns an access token, to be used during API calls that are not public.

        非公開のAPI呼び出しに使用されるトークンを返します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientID:
                  type: string
                clientSecret:
                  type: string
                redirectURI:
                  type: string
                scope:
                  type: string
                code:
                  type: string
                grantType:
                  type: string
              required:
                - clientID
                - clientSecret
                - redirectURI
                - grantType
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                redirect_uri:
                  type: string
                scope:
                  type: string
                code:
                  type: string
                grant_type:
                  type: string
              required:
                - client_id
                - client_secret
                - redirect_uri
                - grant_type
  /oauth/revoke:
    post:
      summary: Revoke token トークンの破棄
      operationId: post-oauth-revoke
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientID:
                  type: string
                clientSecret:
                  type: string
                token:
                  type: string
              required:
                - clientID
                - clientSecret
                - token
            examples: {}
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                token:
                  type: string
              required:
                - client_id
                - client_secret
                - token
        description: ''
      description: |-
        Revoke an access token to make it no longer valid for use.

        アクセストークンを取り消すことで、アクセストークンの使用を無効にすることができます。
  /api/v1/accounts:
    post:
      summary: Register an account アカウントの登録
      operationId: post-api-v1-accounts
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      description: |-
        Creates a user and account records. Returns an account access token for the app that initiated the request. The app should save this token for later, and should wait for the user to confirm their account by clicking a link in their email inbox.

        ユーザーとアカウントのレコードを作成します。要求を開始したアプリのアカウント アクセストークンを返します。アプリはこのトークンを後で使用できるように保存し、ユーザーが電子メールの受信トレイにあるリンクをクリックしてアカウントを確認するのを待つ必要があります。
      parameters:
        - schema:
            type: string
          in: header
          required: true
          name: Authorization
          description: Bearer <app token>
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                agreement:
                  type: string
                locale:
                  type: string
              required:
                - username
                - email
                - password
                - agreement
                - locale
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reason:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                agreement:
                  type: string
                locale:
                  type: string
              required:
                - username
                - email
                - password
                - agreement
                - locale
  /api/v1/accounts/verify_credentials:
    get:
      summary: Verify account credentials アカウントの資格情報を確認
      tags: []
      operationId: get-api-v1-accounts-verify_credentials
      description: |-
        Test to make sure that the user token works.

        トークンが機能するかをテストします。
      parameters:
        - schema:
            type: string
          in: header
          required: true
          name: Authorization
          description: Bearer <user token>
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: string
                  username:
                    type: string
                  acct:
                    type: string
                  displayName:
                    type: string
                  locked:
                    type: boolean
                  bot:
                    type: boolean
                  createdAt:
                    type: string
                  note:
                    type: string
                  url:
                    type: string
                  avatar:
                    type: string
                  avatarStatic:
                    type: string
                  followersCount:
                    type: number
                  followingCount:
                    type: number
                  statusesCount:
                    type: number
                  lastStatusAt:
                    type: string
                  source:
                    type: object
                    properties:
                      privacy:
                        type: string
                      sensitive:
                        type: boolean
                      language:
                        type: string
                      note:
                        type: string
                      fields:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                            verifiedAt:
                              type: string
                      followRequestsCount:
                        type: number
                  emojis:
                    type: array
                    items:
                      type: object
                      properties:
                        shortcode:
                          type: string
                        url:
                          type: string
                        staticURL:
                          type: string
                        visibleInPicker:
                          type: boolean
                  fields:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                        verifiedAt:
                          type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
  /api/v1/accounts/update_credentials:
    patch:
      summary: Update account credentials アカウントの資格情報の更新
      operationId: patch-api-v1-accounts-update_credentials
      responses:
        '200':
          description: OK
      description: |-
        Update the user's display and preferences.

        ユーザーの設定や表示内容を更新します。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer <user token>
          required: true
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                discoverable:
                  type: string
                bot:
                  type: string
                display_name:
                  type: string
                note:
                  type: string
                avatar:
                  type: string
                header:
                  type: string
                locked:
                  type: string
                source:
                  type: string
                fields_attributes:
                  type: string
          application/json:
            schema:
              type: object
              properties:
                discoverable:
                  type: string
                bot:
                  type: string
                displayName:
                  type: string
                note:
                  type: string
                avatar:
                  type: string
                header:
                  type: string
                locked:
                  type: string
                source:
                  type: string
                fieldsAttributes:
                  type: string
        description: ''
