openapi: 3.0.0
info:
  title: Technopolis
  version: 1.0.0
  description: A Federated micro blogging platform inspired by Misskey.
  license:
    name: GNU Free Documentation License Version 1.3
    url: 'https://www.gnu.org/licenses/fdl-1.3.txt'
  contact:
    name: 銀猫さん
    url: 'https://www.sc3.fun'
    email: silverscat_3@mail.sc3.fun
servers:
  - url: 'http://tp.example.org/api/v1'
    description: Example host
paths:
  /app:
    post:
      summary: Create an application
      operationId: post-app
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  website:
                    type: string
                  redirect_uri:
                    type: string
                  client_id:
                    type: string
                  client_secret:
                    type: string
              examples:
                example:
                  value:
                    id: e07bbac7-5189-4f2b-ad9e-f53c7af3954e
                    name: example app
                    website: null
                    redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'
                    client_id: EXAMPLE OF THE CLIENT ID
                    client_secret: EXAMPLE OF THE CLIENT SECRET
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_name:
                  type: string
                  description: A name for your application.
                redirect_uris:
                  type: string
                  description: 'Where the user should be redirected after authorization. To display the authorization code to the user instead of redirecting to a web page, use urn:ietf:wg:oauth:2.0:oob in this parameter.'
                scpoes:
                  type: string
                  description: 'Space separated list of scopes. If none is provided, defaults to read.'
                website:
                  type: string
                  description: A URL to the homepage of your application
              required:
                - client_name
                - redirect_uris
            examples: {}
        description: 'Store the client_id and client_secret in your cache, as these will be used to obtain OAuth tokens.'
      description: Create a new application to obtain OAuth2 credentials.
  /app/verify_credentials:
    get:
      summary: Verify your app works
      tags: []
      responses: {}
      operationId: get-app-verify_credentials
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer <app token here>'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
            examples:
              example:
                value:
                  name: example app
                  website: null
        description: 'If the Authorization header was provided with a valid token, you should see your app returned as an Application entity.'
      description: "Confirm that the app's OAuth2 credentials work."
components:
  schemas: {}
