openapi: 3.0.0
info:
  title: technopolis
  version: 1.0.0
  license:
    name: GNU Free Documentation License Version 1.3
    url: 'https://www.gnu.org/licenses/fdl-1.3.txt'
servers:
  - url: 'http://technopolis.example/api/v1'
paths: {}
components:
  schemas: {}
