openapi: 3.0.0
info:
  title: technopolis
  version: 1.0.0
  license:
    name: GNU Free Documentation License Version 1.3
    url: 'https://www.gnu.org/licenses/fdl-1.3.txt'
servers:
  - url: 'http://technopolis.example'
    description: ''
paths:
  /api/v1/apps:
    post:
      summary: Create an application アプリケーションの作成
      operationId: post-apps
      description: |-
        Create new application to obtain OAuth2 credentials.

        OAuth2資格を取得するためのアプリケーションを作成します。
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_name:
                  type: string
                redirect_uris:
                  type: string
                scopes:
                  type: string
                website:
                  type: string
              required:
                - client_name
                - redirect_uris
            examples: {}
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  type: string
                redirectURIs:
                  type: string
                scopes:
                  type: string
                website:
                  type: string
              required:
                - clientName
                - redirectURIs
            examples: {}
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  website:
                    type: string
                  redirect_uris:
                    type: string
                  client_id:
                    type: string
                  client_secret:
                    type: string
              examples:
                example:
                  value:
                    id: 1043b2e7-a225-467c-9995-73eb33ae6f1e
                    name: Example of the application
                    website: null
                    redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'
                    client_id: EXAMPLE OF CLIENT ID
                    client_secret: EXAMPLE OF CLIENT SECRET
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
    parameters: []
  /api/v1/apps/verify_credentials:
    get:
      summary: Verify your app works アプリケーションの動作確認
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  website:
                    type: string
              examples:
                example:
                  value:
                    name: Example of application
                    website: null
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      operationId: get-apps-verify_credentials
      description: |-
        Confirm that the app's OAuth2 credentials work.

        アプリケーションのOAuth2認証情報が正しく機能することを確認します。
      parameters:
        - schema:
            type: string
            example: 'Bearer <OAuth2 token>'
            pattern: ''
          in: header
          name: Authorization
          required: true
          description: 'Bearer <OAuth2 token here>'
    parameters: []
  /oauth/authorize:
    get:
      summary: Authorize a user ユーザーの承認
      tags: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      operationId: get-oauth
      description: |-
        Displays an authorization form to the user. If approved, it will create and return an authorization code, then redirect to the desired redirect_uri, or show the authorization code if urn:ietf:wg:oauth:2.0:oob was requested. The authorization code can be used while requesting a token to obtain access to user-level methods.

        承認フォームをユーザーに表示します。 承認されると認証コードを作成して返し、目的のredirect_uriにリダイレクトするか、urn:ietf:wg:oauth:2.0:oobがリクエストされた場合は認証コードを表示します。 ユーザーレベルのメソッドへのアクセスを取得するためにトークンを要求するときに認証コードを使用することができます。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                force_login:
                  type: boolean
                responseType:
                  type: string
                clientID:
                  type: string
                redirectURI:
                  type: string
                scope:
                  type: string
              required:
                - responseType
                - clientID
                - redirectURI
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                force_login:
                  type: boolean
                response_type:
                  type: string
                client_id:
                  type: string
                redirect_uri:
                  type: string
                scope:
                  type: string
              required:
                - response_type
                - client_id
                - redirect_uri
            examples: {}
        description: ''
    parameters: []
  /oauth/token:
    post:
      summary: Obtain a token トークンの入手
      operationId: post-oauth-token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  scope:
                    type: string
                  created_at:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      description: |-
        Returns an access token, to be used during API calls that are not public.

        非公開のAPI呼び出しに使用されるトークンを返します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientID:
                  type: string
                clientSecret:
                  type: string
                redirectURI:
                  type: string
                scope:
                  type: string
                code:
                  type: string
                grantType:
                  type: string
              required:
                - clientID
                - clientSecret
                - redirectURI
                - grantType
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                client_secret:
                  type: string
                redirect_uri:
                  type: string
                scope:
                  type: string
                code:
                  type: string
                grant_type:
                  type: string
              required:
                - client_id
                - client_secret
                - redirect_uri
                - grant_type
  /oauth/revoke:
    post:
      summary: Revoke token トークンの破棄
      operationId: post-oauth-revoke
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_description:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientID:
                  type: string
                clientSecret:
                  type: string
                token:
                  type: string
              required:
                - clientID
                - clientSecret
                - token
        description: ''
components:
  schemas: {}
  securitySchemes: {}
